### ISSUE TITLE
Error parsing sitemap.xml file when custom elements are added 

### ISSUE THREAD

**Issue by frasy** [daveoconnor/site-map-parser#1]
According with https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd format as per https://www.sitemaps.org/protocol.html standard different custom elements can be added inside the <url> tag
```xml
<xsd:complexType name="tUrl">
<xsd:annotation>
<xsd:documentation>
Container for the data needed to describe a document to crawl.
</xsd:documentation>
</xsd:annotation>
<xsd:sequence>
<xsd:element name="loc" type="tLoc"/>
<xsd:element name="lastmod" type="tLastmod" minOccurs="0"/>
<xsd:element name="changefreq" type="tChangeFreq" minOccurs="0"/>
<xsd:element name="priority" type="tPriority" minOccurs="0"/>
<xsd:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
</xsd:sequence>
</xsd:complexType>
```

If those custom elements don't have text <element>text</element> the process fails trying to get the text from an element which doesn't contain it:
```xml
<url>
<loc>url</loc>
<link href="url" />
</url>
```
(code line where fails: https://github.com/daveoconnor/site-map-parser/blob/cda5a90999ef14f17e04572b078e9fdbea8d994c/sitemapparser/url_set.py#L18)

As custom elements are not the main concern of this parser, I think the process shouldn't fail and should continue processing the xml (we have to keep in mind that the xml is correctly structured).

As a suggestion, if an element is not recognised as per https://www.sitemaps.org standard, avoid loading it and any value related.

**Comment by daveoconnor** [comment]
Thank you very much for your very clear report and explanation, and your pull request. I've merged it, added tests, and pushed a new release to Pypi.

Thanks again!
