### ISSUE TITLE
how to produce actual csv file?

### ISSUE THREAD

**Issue by nicpederson** [daveoconnor/site-map-parser#8]
the script runs fine, but it doesn't actually export a csv. how do i do that?

**Comment by daveoconnor** [comment]
Hi, you can use normal shell functionality to do that if you're on a platform that supports that. 

An example from the README that you will need to adjust:

`smapper $url > /tmp/data.csv`

The > /tmp/data.csv is a shell way of saying "take the output of the command and redirect it to the file at /tmp/data.csv".

I don't know how to do this on windows. In that case this might help: https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
